<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookings Report</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@3.3.3/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="font-sans text-gray-800 p-6">

    <h1 class="text-2xl font-bold text-blue-800 border-b-2 border-blue-600 pb-2 mb-6">
        Bookings Report
    </h1>

    <p class="mb-6 text-sm text-gray-600">Generated at: {{ now()->format('Y-m-d H:i') }}</p>

    <!-- STATISTICS TABLE -->
    <h2 class="text-xl font-semibold text-blue-700 mb-2">Statistics Overview</h2>
    <table class="w-full border border-gray-300 mb-6">
        <tbody>
            <tr class="bg-gray-100">
                <td class="p-2 font-semibold">Total Bookings</td>
                <td class="p-2">{{ $stats['total'] }}</td>
            </tr>
            <tr>
                <td class="p-2 font-semibold">Pending</td>
                <td class="p-2">{{ $stats['pending'] }}</td>
            </tr>
            <tr class="bg-gray-100">
                <td class="p-2 font-semibold">Approved</td>
                <td class="p-2">{{ $stats['approved'] }}</td>
            </tr>
            <tr>
                <td class="p-2 font-semibold">Canceled</td>
                <td class="p-2">{{ $stats['canceled'] }}</td>
            </tr>
            <tr class="bg-gray-100">
                <td class="p-2 font-semibold">Completed</td>
                <td class="p-2">{{ $stats['completed'] }}</td>
            </tr>
            <tr>
                <td class="p-2 font-semibold">Rescheduled</td>
                <td class="p-2">{{ $stats['rescheduled'] }}</td>
            </tr>
            <tr class="bg-gray-100">
                <td class="p-2 font-semibold">Rejected</td>
                <td class="p-2">{{ $stats['rejected'] }}</td>
            </tr>
        </tbody>
    </table>

    <!-- TOP EMPLOYEES -->
    <h2 class="text-xl font-semibold text-blue-700 mb-2">Top Employees</h2>
    <table class="w-full border border-gray-300 mb-6">
        <thead class="bg-blue-600 text-white">
            <tr>
                <th class="p-2 text-left">Employee</th>
                <th class="p-2 text-left">Total Bookings</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['top_employees'] as $emp)
                <tr class="even:bg-gray-100">
                    <td class="p-2">{{ $emp->employee->name ?? 'N/A' }}</td>
                    <td class="p-2">{{ $emp->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- BOOKINGS BY CITY -->
    <h2 class="text-xl font-semibold text-blue-700 mb-2">Bookings by City</h2>
    <table class="w-full border border-gray-300 mb-6">
        <thead class="bg-blue-600 text-white">
            <tr>
                <th class="p-2 text-left">City</th>
                <th class="p-2 text-left">Total Bookings</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stats['by_city'] as $city)
                <tr class="even:bg-gray-100">
                    <td class="p-2">{{ $city->city }}</td>
                    <td class="p-2">{{ $city->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <footer class="text-center text-gray-500 text-sm mt-8">
        &copy; {{ date('Y') }} Property Management System | Generated by Admin
    </footer>

</body>
</html>
